### ISSUE TITLE
Missing files and build error

### ISSUE THREAD

**Issue by CodingAna** [AmazingSupDawg/DokkOS#1]
Hey there, I cloned this repo and tried opening it via Xcode but it's missing the `.xcodeproj` file. Could you provide the full Xcode project file to easily import it into Xcode?
When I manually created the project and copied the files I ran into a compiler error because in `DokkOSApp.swift` the line `PeersView()` was missing the `peersVm` parameter (which I changed to `PeersView(peersVm: PeersVm())`). I was able to build and run the application afterwards.
Is there any chance you are still continuing development?

**Comment by jackkroll** [comment]
Hey! It's been a minute since I've worked on this. I believe I uploaded the project file properly, not sure though. Unfortunately I have no intentions to continue development, but I hope this could be of some use for you.

**Comment by CodingAna** [comment]
Hi, thanks! That made cloning and setting it up a little easier :)
I'll see how can build up onto this, but its a great start already, thank you for that!
